server:
  port: 9040

# 注册到Eureka服务中心
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://SpringCloudEurekaServerA:9020/eureka,http://SpringCloudEurekaServerB:9021/eureka
  instance:
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT

spring:
  application:
    name: Study-Cloud-Config
  cloud:
    config:
      server:
        # 从GitHub上获取配置文件信息
        git:
          uri: https://github.com/lu6666666/SpringCloud-Config.git
          username: lu6666666
          password: lx991013...
          search-paths:
            - SpringCloud-Config
          # skip-ssl-validation: true
      # 读取分支
      label: master
  rabbitmq:
    host: 192.168.43.129
    # 下面三个可以不配置 使用默认的（前提是账号密码没有修改过）
    port: 5672
    username: admin
    password: 123456
    virtual-host: /study

#建议暴露所有的端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
